name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy webhook-vendas Function
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run Deploy Command
        run: |
          supabase functions deploy webhook-vendas --project-ref "${{ secrets.SUPABASE_PROJECT_ID }}" --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}" --no-verify-jwt
